Fix errors showing command usage

diff --git a/bin/oltp-setup-env b/bin/oltp-setup-env
--- a/bin/oltp-setup-env
+++ b/bin/oltp-setup-env
@@ -30,7 +30,8 @@ then
   # User does not provide RWLOADSIM_PATH, so $RWLOLTP_NAME.rwl must be in current directory
   if test ! -r $RWLOLTP_NAME.rwl 
   then
-    echo "$RWLOLTP_NAME.rwl cannot be read - you must be in your projects working directory" 1>&2
+    echo "$RWLOLTP_NAME.rwl cannot be read - you must either be in your project directory" 1>&2
+    echo "containing $RWLOLTP_NAME.rwl or include it in the RWLOADSIM_PATH environment" 1>&2
     test x$1 = x-H || exit 1
   fi
   export RWLOADSIM_PATH=$basedir/oltp
@@ -47,7 +48,7 @@ else
   if test $found = no
   then
     echo "$RWLOLTP_NAME.rwl not found in RWLOADSIM_PATH" 1>&2
-    exit 1;
+    test x$1 = x-H || exit 1
   fi
   # basedir/oltp comes last such we we find modified copies of
   # distributed rwl files in users RWLOADSIM_PATH
