rwlerror utility; major update to error messaging

diff --git a/bin/rwloadsim b/bin/rwloadsim
--- a/bin/rwloadsim
+++ b/bin/rwloadsim
@@ -77,5 +77,5 @@ do
   fi
 done
 
-echo "RWL-243: error: Cannot find $rwloadsim executable in PATH" 1>&2
+echo "RWL-186: error: Cannot find $rwloadsim executable in PATH" 1>&2
 exit 1
